blog/urls.py
from django.urls import path
from .import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    # path('', views.post_list, name='post_list'),
    # path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    # path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>-<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('post/add/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>-<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>-<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('reference/', include('reference.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, 
            name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
    path('api/', include('blog.api.urls', namespace='api')),
    path('api2/', include('reference.api.urls', namespace='api')),
    path('api_auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reference/api/urls.py
from django.urls import path
from . import views

app_name='reference'
urlpatterns = [
    path('list/', views.ReferenceListView.as_view(), name='api_reference_list'),
    path('list/<int:pk>/', views.ReferenceDetailView.as_view(), name='api_reference_detail'),
]

reference/urls.py
from django.urls import path
from .import views
from .feeds import LatestReferencesFeed

app_name = 'reference'
urlpatterns = [
    path('', views.ReferenceListView.as_view(), name='reference_list'),
    # path('reference/<int:pk>-<slug:slug>/', views.ReferenceDetailView.as_view(), name='reference_detail'),
    path('feed/', LatestReferencesFeed(), name='reference_feed'),
    path('reference/add/', views.ReferenceCreateView.as_view(), name='reference_create'),
    path('reference/<int:pk>-<slug:slug>/update/', views.ReferenceUpdateView.as_view(), name='reference_update'),
    path('reference/<int:pk>-<slug:slug>/delete/', views.ReferenceDeleteView.as_view(), name='reference_delete'),
]

reference/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse_lazy

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
            .filter(status='published')

class Reference(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reference_list')
    description = models.TextField()
    link = models.URLField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)
        db_table = "reference"

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse_lazy('reference:reference_detail', kwargs={ 'pk': self.id, 'slug': self.slug })

reference/api/views.py
from rest_framework import generics, mixins, permissions
from ..models import Reference
from .serializers import ReferenceSerializer
from django.contrib.auth import get_user_model
from .permissions import IsAuthorOrReadOnly
from django.utils.text import slugify

class ReferenceListView(generics.ListCreateAPIView):
    queryset = Reference.objects.all()
    serializer_class = ReferenceSerializer   
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        if serializer.is_valid():
            serializer.save(author=self.request.user,
                            status='published',
                            slug=slugify(serializer.validated_data['title'], allow_unicode=True))

class ReferenceDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Reference.objects.all()
    serializer_class = ReferenceSerializer   
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsAuthorOrReadOnly]

    def perform_update(self, serializer):
        if serializer.is_valid():
            serializer.save(slug=slugify(serializer.validated_data['title'], allow_unicode=True))

reference/views.py
from django.shortcuts import render, get_object_or_404
from .models import Reference
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import (SearchVector, 
                                            SearchQuery, 
                                            SearchRank)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.text import slugify

class ReferenceListView(LoginRequiredMixin, ListView):
    queryset = Reference.published.all().order_by('-created')
    context_object_name = 'references'
    paginate_by = 2
    template_name = 'reference/page/list.html'
    
    def get_queryset(self):
        qs = super().get_queryset()
        tag_slug = self.kwargs.get('tag_slug')

        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            qs = qs.filter(tags__in=[tag])
            self.tag = tag
        else:
            self.tag = None
        
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.tag:
            context['tag'] = self.tag

        return context

# class ReferenceDetailView(LoginRequiredMixin, FormView):
#     form_class = FormView
#     template_name = 'reference/page/detail.html'

#     def get_initial(self):
#         pk = self.kwargs.get('pk')
#         slug = self.kwargs.get('slug')
#         self.reference = get_object_or_404(Reference, pk=pk, slug=slug)
#         return super().get_initial()

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['reference'] = self.reference
#         return context


class ReferenceCreateView(LoginRequiredMixin, CreateView):
    model = Reference
    fields = ['title', 'link', 'description']
    template_name = 'reference/page/reference_form.html'
    success_url = reverse_lazy('reference:reference_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.status = 'published'
        form.instance.slug = slugify(form.instance.title, allow_unicode=True)

        return super().form_valid(form)

class ReferenceUpdateView(LoginRequiredMixin, UpdateView):
    model = Reference
    fields = ['title', 'link', 'description']
    template_name = 'reference/page/reference_form.html'
    success_url = reverse_lazy('reference:reference_list')
    query_pk_and_slug = True

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author = self.request.user)

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title, allow_unicode=True)
        return super().form_valid(form)

class ReferenceDeleteView(LoginRequiredMixin, DeleteView):
    model = Reference
    template_name = 'reference/page/reference_confirm_delete.html'
    success_url = reverse_lazy('reference:reference_list')
    query_pk_and_slug = True

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author = self.request.user)

reference/templates/reference/page/detail.html
{% extends 'reference/base.html' %}
{% load reference_tags %} -->

{% block title %}
    {{ reference.title }}
{% endblock title %}

{% block content %}
    <h1>
        {{ reference.title }}
    </h1>
    <p clas="date">
        Published {{ reference.publish }} by {{ reference.author}}
    </p>
    {{ reference.link|markdown }}
    {{ reference.description|markdown }}
{% endblock content %}

reference/templates/reference/page/latest_references.html
<ul>
    {% for reference in latest_references %}
        <li>
            <a href="{{ reference.get_absolute_url }}">
                {{ reference.title }}
            </a>
        </li>
    {% endfor %}
</ul>

reference/templates/reference/page/list.html
{% extends 'reference/base.html' %}
{% load reference_tags %}

{% block title %}
    My Reference
{% endblock title %}

{% block content %}

    <h1>Reference List</h1>
    <a href="{% url 'reference:reference_create' %}" class="btn btn-success">Add Reference</a>
    </br></br>
    <ul>
        {% for reference in references %}
            <li>
                <h2>
                    {{ reference.title }}         
                </h2>
                <p class="date">
                    Published {{ reference.publish }} by {{ reference.author }}
                </p>
                <a href="{{ reference.link }}">{{ reference.link }}</a>
                {{ reference.description|markdown }}
                {% if reference.author == request.user %}
                    <a href="{% url 'reference:reference_update' reference.id reference.slug %}" class="btn btn-warning">Update Post</a> 
                    <a href="{% url 'reference:reference_delete' reference.id reference.slug %}" class="btn btn-danger">Delete Post</a>
                {% endif %}
                </li><br>
            </li>
        {% endfor %}
    </ul>
    
    {% include "pagination.html" with page=page_obj %}
{% endblock content %}

reference/templates/reference/page/reference_confirm_delete.html
{% extends 'reference/base.html' %}

{% block title %}
    Delete Reference
{% endblock title %}

{% block content %}
    <h1>Delete Reference</h1>
    <form action="" method="post">
        <p>Are you sure you want to delete this item <strong>{{ object }}</strong>?</p>
        {% csrf_token %}
        <p><input type="submit" value="Confirm"></p>
    </form>
{% endblock content %}
        

reference/templates/reference/page/reference_form.html
{% extends 'reference/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create/Update Reference
{% endblock title %}

{% block content %}
    <h1>
        {% if 'add' in request.path|slice:'-4:' %}
            Create Reference
        {% else %}
            Update Reference
        {% endif %}
    </h1>
    <form action="" method="post">
        {% for field in form %}
            <div class="row">
                <div class="col">
                    {{ field|as_crispy_field }}
                </div>
            </div>
        {% endfor %}
        {% csrf_token %}
        </br>
        <p><input type="submit" 
            value="{% if 'add' in request.path|slice:'-4:' %}
                        Create
                    {% else %}
                         Update
                    {% endif %}">
        </p>
    </form>
{% endblock content %}
        